services:
  postgres:
    image: postgres:15
    container_name: postgres_cbo
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: cbo_sinonimos
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis_cbo
    ports:
      - "6379:6379"

  flask:
    build:
      context: .
      dockerfile: python.Dockerfile
    container_name: flask_cbo
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:123456@postgres:5432/cbo_sinonimos
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "5000:5000"
    command: >
      sh -c "python load_csv_to_postgres.py && python app.py"
